NODE_ENV=development
PORT=5000

MONGO_URI=mongodb://127.0.0.1:27017/lms

JWT_SECRET=<YOUR_LONG_JWT_SECRET>
JWT_EXPIRY=5d

CLOUDINARY_CLOUD_NAME=dlpumfhps
CLOUDINARY_API_KEY=347572427157142
CLOUDINARY_API_SECRET=Gc0msKbwRuW7X7C1HbfHJT9X1lk


SMTP_HOST=<YOUR_SMTP_HOST>
SMTP_PORT=<YOUR_SMTP_PORT>
SMTP_USERNAME=<YOUR_SMTP_USERNAME>
SMTP_PASSWORD=<YOUR_SMTP_PASSWORD>
SMTP_FROM_EMAIL=<YOUR_SMTP_FROM_EMAIL>

RAZORPAY_KEY_ID=<YOUR_RAZORPAY_KEY>
RAZORPAY_SECRET=<YOUR_RAZORPAY_SECRET>
RAZORPAY_PLAN_ID=<YOUR_RAZORPAY_PLAN_ID>

FRONTEND_URL=http://localhost:5173

